export enum ActionType {
  INIT_GET_WIDGET_LIST = "INIT_GET_WIDGET_LIST",
  GET_WIDGET_SUCCESS = "GET_WIDGET_SUCCESS",
  GET_WIDGET_ERROR = "GET_WIDGET_ERROR",

  INIT_CC_WIDGET_1 = "INIT_CC_WIDGET_1",
  CC_WIDGET_1_SUCCESS = "CC_WIDGET_1_SUCCESS",
  CC_WIDGET_1_ERROR = "CC_WIDGET_1_ERROR",

  INIT_CC_WIDGET_2 = "INIT_CC_WIDGET_2",
  CC_WIDGET_2_SUCCESS = "CC_WIDGET_2_SUCCESS",
  CC_WIDGET_2_ERROR = "CC_WIDGET_2_ERROR",
}
