export enum ActionType {
  INIT_GET_SUBSCRIBER_DASHBOARD = "INIT_GET_SUBSCRIBER_DASHBOARD",
  GET_SUBSCRIBER_DASHBOARD_SUCCESS = "GET_SUBSCRIBER_DASHBOARD_SUCCESS",
  GET_SUBSCRIBER_DASHBOARD_ERROR = "GET_SUBSCRIBER_DASHBOARD_ERROR",

  INIT_CC_WIDGET_1 = "INIT_CC_WIDGET_1",
  CC_WIDGET_1_SUCCESS = "CC_WIDGET_1_SUCCESS",
  CC_WIDGET_1_ERROR = "CC_WIDGET_1_ERROR",

  INIT_CC_WIDGET_2 = "INIT_CC_WIDGET_2",
  CC_WIDGET_2_SUCCESS = "CC_WIDGET_2_SUCCESS",
  CC_WIDGET_2_ERROR = "CC_WIDGET_2_ERROR",
}
