/**
 * Filename : App.tsx \
 * Description : This file renders the home page \
 * Extentia: Copyright (c) 2022
 */

import { useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { ModalComponent } from 'components';

const Home: NextPage = (): JSX.Element => {
    const [showModal, setShowModal] = useState(false);
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="mx-[40px] mt-[64px]">
                <button type="button" onClick={() => setShowModal((prev) => !prev)}>
                    Modal
                </button>
                <ModalComponent
                    showModal={showModal}
                    handleShowModal={() => setShowModal((prev) => !prev)}
                />
            </main>
        </>
    );
};

export default Home;
