import { useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useActions } from "hooks/useActions";
import { useTypedSelector } from "hooks/useTypedSelector";
import { Content } from "components";

const Home: NextPage = () => {
	const { getSubscribersDashboard } = useActions();
	useEffect(() => {
		getSubscribersDashboard({ subscriberId: 1 });
	}, []);

	const { isError, isLoading, data } = useTypedSelector(
		({ widgetList }) => widgetList
	);

	if (isLoading) return <>Loading...</>;
	if (isError) return <>Something went wrong !!</>;

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Content listOfWidgets={data} />
		</div>
	);
};

export default Home;
