/**
 * Filename : App.tsx \
 * Description : This file renders the home page \
 * Extentia: Copyright (c) 2022
 */

import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { SvgIconComponent, InputComponent, ButtonComponent } from 'components';
import { LoggerService } from 'services/logger.service';

const Home: NextPage = (): JSX.Element => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="flex items-center mb-[30px]">
                <SvgIconComponent className="w-6 h-6" icon="BreadCrumIcon" />
                <span className="ml-2 font-light">Home</span>
                <span className="mx-2">{'>'}</span>
                <span className="font-bold">Search Results</span>
            </div>
            <div className="mb-2">
                <div className="w-[968px] inline-block">
                    <InputComponent
                        withIcon
                        icon={<span className="w-5 h-2 mx-auto">X</span>}
                        placeholder="Top Surgical oncologists in North America"
                    />
                </div>
                <ButtonComponent
                    type="button"
                    onClick={() => LoggerService.log('clicked')}
                    className="p-4 ml-4 bg-white rounded-lg text-orange-default"
                >
                    Save Search
                </ButtonComponent>
            </div>
            <div className="text-xs mb-11">
                <span className="font-semibold">Showing 120 </span>
                <span className="font-lighter">
                    results for “Top Surgical oncologists in North America“
                </span>
            </div>
            <div className="flex items-center justify-between">
                <div>
                    <span className="mr-4 font-semibold">Filters</span>
                    <span className="inline-flex items-center justify-center px-4 py-2 mr-2 text-xs font-light leading-none text-[#E14CB0] bg-[#E14CB0]/[0.08] rounded-full">
                        Cancer Treat Rev <span className="ml-2">X</span>
                    </span>
                    <span className="inline-flex items-center justify-center px-4 py-2 mr-2 text-xs font-light leading-none text-[#1BAEAA] bg-[#1BAEAA]/[0.08] rounded-full">
                        Cancer Treat Rev <span className="ml-2">X</span>
                    </span>
                    <span className="inline-flex items-center justify-center px-4 py-2 mr-2 text-xs font-light leading-none text-[#3E50FE] bg-[#3E50FE]/[0.08] rounded-full">
                        Cancer Treat Rev <span className="ml-2">X</span>
                    </span>
                    <span className="inline-flex items-center justify-center px-4 py-2 mr-2 text-xs font-light leading-none text-[#7A02E4] bg-[#7A02E4]/[0.08] rounded-full">
                        Cancer Treat Rev <span className="ml-2">X</span>
                    </span>
                    <span className="inline-flex items-center justify-center px-4 py-2 mr-2 text-xs font-light leading-none text-[#FD5B1F] bg-[#FD5B1F]/[0.08] rounded-full">
                        ...
                    </span>
                    <span className="inline-flex items-center justify-center px-4 py-2 mr-2 text-xs font-normal leading-none rounded-full text-orange-default">
                        Clear All
                    </span>
                </div>
                <div className="flex items-center">
                    <ButtonComponent
                        type="button"
                        onClick={() => LoggerService.log('clicked')}
                        className="px-4 py-1 mr-4 bg-white rounded-lg text-orange-default"
                    >
                        <div className="flex items-center justify-center">
                            <span>Sort By</span>
                            <span>
                                <SvgIconComponent icon="SortIcon" className="mt-5 ml-2 h-7" />
                            </span>
                        </div>
                    </ButtonComponent>
                    <ButtonComponent
                        type="button"
                        onClick={() => LoggerService.log('clicked')}
                        className="px-4 py-2 mr-4 bg-white rounded-lg text-orange-default"
                    >
                        <SvgIconComponent icon="FilterIcon" className="mt-3 h-7" />
                    </ButtonComponent>
                    <ButtonComponent
                        type="button"
                        onClick={() => LoggerService.log('clicked')}
                        className="px-4 py-2 mr-4 bg-white rounded-lg text-orange-default"
                    >
                        <SvgIconComponent icon="SaveIcon" className="mt-3 h-7" />
                    </ButtonComponent>{' '}
                    <ButtonComponent
                        type="button"
                        onClick={() => LoggerService.log('clicked')}
                        className="px-4 py-2 mr-4 bg-white rounded-lg text-orange-default"
                    >
                        <SvgIconComponent icon="LocationIcon" className="mt-3 h-7" />
                    </ButtonComponent>
                </div>
            </div>
            <div className="flex items-center justify-between mt-6">
                <span className="flex text-sm font-light">
                    <SvgIconComponent className="w-5 h-5 mt-1" icon="LeftArrowIcon" />
                    <span>1-12</span>
                    <span className="mx-2 font-extralight">of</span>
                    <span>1,201</span>
                    <SvgIconComponent className="w-5 h-5 mt-1 ml-3" icon="RightArrowIcon" />
                </span>
                <span className="text-xs font-semibold text-orange-default">Select All</span>
            </div>

            <div className="flex flex-col justify-center h-32 my-4 bg-white rounded p-9">
                <div className="flex items-center">
                    <div>
                        <span className="flex items-center">
                            1 <SvgIconComponent icon="UpArrowGreenIcon" className="h-5 pt-2 mx-2" />
                            <span className="text-gray-400">2</span>
                        </span>
                        <span className="text-sm">Overall</span>
                    </div>
                    <div className="relative w-[60px] h-[60px] mx-4">
                        <Image
                            className="rounded-full"
                            src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60"
                            layout="fill"
                            alt="doctor-image"
                        />
                    </div>
                    <div className="flex flex-col">
                        <span className="font-semibold">Lombardi, Giovanni</span>
                        <span className="font-light">Gastric Oncology</span>
                        <div>
                            <span className="mx-2">x</span>
                            <span className="mx-2">x</span> <span className="mx-2">x</span>{' '}
                            <span className="mx-2">x</span>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
};

export default Home;
